/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MissionControlRouteImport } from './routes/mission-control'
import { Route as MiningReactorRouteImport } from './routes/mining-reactor'
import { Route as GalaxyRouteImport } from './routes/galaxy'
import { Route as IndexRouteImport } from './routes/index'

const MissionControlRoute = MissionControlRouteImport.update({
  id: '/mission-control',
  path: '/mission-control',
  getParentRoute: () => rootRouteImport,
} as any)
const MiningReactorRoute = MiningReactorRouteImport.update({
  id: '/mining-reactor',
  path: '/mining-reactor',
  getParentRoute: () => rootRouteImport,
} as any)
const GalaxyRoute = GalaxyRouteImport.update({
  id: '/galaxy',
  path: '/galaxy',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/mining-reactor': typeof MiningReactorRoute
  '/mission-control': typeof MissionControlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/mining-reactor': typeof MiningReactorRoute
  '/mission-control': typeof MissionControlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/galaxy': typeof GalaxyRoute
  '/mining-reactor': typeof MiningReactorRoute
  '/mission-control': typeof MissionControlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/galaxy' | '/mining-reactor' | '/mission-control'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/galaxy' | '/mining-reactor' | '/mission-control'
  id: '__root__' | '/' | '/galaxy' | '/mining-reactor' | '/mission-control'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GalaxyRoute: typeof GalaxyRoute
  MiningReactorRoute: typeof MiningReactorRoute
  MissionControlRoute: typeof MissionControlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mission-control': {
      id: '/mission-control'
      path: '/mission-control'
      fullPath: '/mission-control'
      preLoaderRoute: typeof MissionControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mining-reactor': {
      id: '/mining-reactor'
      path: '/mining-reactor'
      fullPath: '/mining-reactor'
      preLoaderRoute: typeof MiningReactorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galaxy': {
      id: '/galaxy'
      path: '/galaxy'
      fullPath: '/galaxy'
      preLoaderRoute: typeof GalaxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GalaxyRoute: GalaxyRoute,
  MiningReactorRoute: MiningReactorRoute,
  MissionControlRoute: MissionControlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
